# Generated by Django 4.2.29 on 2026-05-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="学年名称"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="是否当前学年"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "学年",
                "verbose_name_plural": "学年",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="scorerecord",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="score_records",
                to="core.academicyear",
                verbose_name="学年",
            ),
        ),
    ]
